#1
N 0 You miss $N's %s with your pierce.~
$n misses $N's %s with $s pierce.~
$n misses your %s with $s pierce.~
N 1 You graze $B$N$b on the %s with your pierce.~
$n grazes $B$N$b on the %s with $s pierce.~
$n grazes $Byou$b on the %s with $s pierce.~
N 3 You barely pierce $B$N$b's %s.~
$n barely pierces $B$N$b's %s.~
$n barely pierces $Byour$b %s.~
N 6 You pierce $B$N$b's %s.~
$n pierces $B$N$b's %s.~
$n pierces $Byour$b %s.~
N 9 You pierce $B$N$b hard on the %s.~
$n pierces $B$N$b hard on the %s.~
$n pierces $Byou$b hard on the %s.~
N 13 You pierce $B$N$b very hard on the %s.~
$n pierces $B$N$b very hard on the %s.~
$n pierces $Byou$b very hard on the %s.~
N 16 You pierce $B$N$b extremely hard on the %s.~
$n pierces $B$N$b extremely hard on the %s.~
$n pierces $Byou$b extremely hard on the %s.~
N 21 You wound $B$N$b on $S %s with a brutal pierce.~
$n brutally pierces $B$N$b's %s.~
$n brutally pierces $Byour$b %s~
D 0 You pierce through $B$N$b's %s, killing $M.~
$n pierces through $B$N's$b %s, killing $M.~
$n pierces through $Byour$b %s, killing you.~
#2
N 0 You miss $N's %s with your crush.~
$n misses $N's %s with $s crush.~
$n misses your %s with $s crush.~
N 1 You crush $B$N$b's %s.~
$n crushes $B$N$b's %s.~
$n crushes $Byou$b's %s.~
N 10 You crush $B$N$b hard on the %s.~
$n crushes $B$N$b hard on the %s.~
$n crushes $Byou$b hard on the %s.~
N 15 You connect strong with your crush to $B$N$b's %s.~
$n connects strong with his crush to $B$N$b's %s.~
$n connects strong to $Byour$b %s with his crush.~
N 23 With a skillful swing, you crush $B$N$b's %s.~
$n moves in skillfully and crushes $B$N$b's %s.~
$n ducks around and skillfully crushes $Byour$b %s.~
D 0 You crush $B$N$b's side, breaking $S spine~
$n crushes $B$N$b's side, breaking $S spine.~
$n crushes $Byour$b spine, breaking your spine.~
#3
N 0 You miss $N's %s with your slash.~
$n misses $N's %s with $s slash.~
$n misses your %s with $s slash.~
N 1 You slash slowly, and only end up with a small piece of $B$N$b's %s.~
$n slashes slowly, and only ends up with a small piece of $B$N$b's %s.~
$n slashes slowly, and only ends up with a small piece of $Byour$b %s.~
N 4 With a quick twist you manage to barely slash $B$N$b's %s.~
With a quick twist, $n manages to barely slash $B$N$b's %s.~
With a quick twist, $n barely manages to slash $Byour$b %s.~
N 7 You slash $B$N$b's %s, opening a small cut.~
$n slashes $B$N$b's %s, opening a small cut.~
$n slashes $Byour$b %s, opening a small cut.~
N 10 You slash $B$N$b hard on the %s.~
$n slashes $B$N$b hard on the %s.~
$n slashes $Byou$b hard on the %s.~
N 15 You slash $B$N$b very hard on the %s.~
$n slashes $B$N$b on the %s, connecting hard.~
$n slashes $Byou$b very hard on the %s.~
N 23 You land a double-slash to $B$N$b's %s.~
$n lands a skillful double-slash on $B$N$b's %s.~
$n slashes skillfully and opens two gashes on $Byour$b %s.~
N 35 You slash $B$N's$b %s, inflicting a grievous wound.~
$n slashes $B$N$b on the %s, inflicting a grievous wound.~
$n slashes $Byou$b on your %s, inflicting a grievous wound.~
D 0 You slash through $B$N$b's neck, severing $S head from $S body.~
$n slashes through $B$N$b's neck, decapitating $M!~
$n slashes through $Byour$b neck, your head is severed from your body...~
#4
N 0 You attempt to hit $N's %s with the bottle but miss.~
$n attempts to hit $N's %s with a bottle but misses.~
$n attempts to hit your %s with a bottle but misses.~
N 1 You smash a bottle against $B$N$b's %s.~
$n smashes a bottle against $B$N$b's %s.~
$n smashes a bottle against $Byour$b %s.~
N 10 Shards fly everywhere as you club $B$N$b's %s with a bottle.~
Shards fly everywhere as $n clubs $B$N$b's %s with a bottle.~
Shards fly everywhere as $n clubs $Byour$b %s with a bottle.~
D 0 You shatter a bottle on $B$N$b's %s, fracturing both into a thousand
pieces.~
$n shatters a bottle on $B$N$b's %s, fracturing both into a thousand pieces.~
$n shatters a bottle on $Byour$b %s, fracturing both into a thousand pieces.~
#5
N 0 You swing a wild punch at $N's %s but miss.~
$n swings a wild punch at $N's %s and misses.~
$n swings a wild punch at your %s and misses.~
N 1 You graze $B$N$b's %s slightly as $E barely dodges your punch.~
$n grazes $B$N$b's %s as $E barely dodges $n's punch.~
$n grazes $Byour$b %s slightly as you barely dodge $S punch.~
N 4 You get a piece of $B$N$b's %s with your jab.~
$n gets a piece of $B$N$b's %s with $S jab.~
$n gets a piece of $Byour$b %s with $S jab.~
N 7 You connect an uppercut to $B$N$b's %s, shaking $M slightly.~
$n connects an uppercut to $B$N$b's %s, shaking $M slightly.~
$n connects an uppercut to $Byour$b %s, shaking you slightly.~
N 10 Your fist clubs $B$N$b solidly in the %s.~
$n's fist clubs $B$N$b solidly in the %s.~
$n's fist clubs $Byou$b solidly in the %s.~
N 13 With a powerful swing, you slam your fist into $B$N$b's %s.~
$n sidesteps, and with a powerful swing slams his fist into $B$N$b's %s.~
$n sidesteps, and with a powerful swing slams his fist into $Byour$b %s.~
D 0 You ram your fingers right through $B$N$b's eyes, ripping $S face off~
$n jams $S fingers through $B$N$b's eyes, ripping $S face off~
$n jams $S fingers into $Byour$b eyes and rips your face off~
#-1